# Generated by Django 4.1.4 on 2023-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Date_Added', models.DateField()),
                ('Installer_Link', models.CharField(max_length=2083)),
                ('App_Developer_Website', models.CharField(max_length=2083)),
            ],
        ),
    ]
