# Generated by Django 4.1.4 on 2023-01-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Installers',
            new_name='Installer',
        ),
    ]
